# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mxTO/V43JgqnJQfNYzSTmJ36ny8SF5gAOr7sr6PmK5EKy/z3wVXYH721tyfOLqxCT8E0m2rmULCkjGFSikrWVwJcDhePaLqlou4sAgAt6a+cVfBdTxZ/NkvlADmrdDIyzdeDJDECHxs+0uDXuAVJ91l+kWXAfoYitoYz9FB4GtZKmbzz5zjoUfkZUp0Bkl03M9xS0qb4c9n8Ud4eWS3vlq8HhPiFY20UCRt5pla+eZ+ijW0x/dqev9xI579ITgoRZJZfa0ODu0Gyh7TnSugBp/qFJ0sJSEBq5kSfc4b4HxTwjArYViwFsq9rrizim3gQDW4O+0ERjguvnrmwCDa3mAJBSGluewj3Fk2mscPzPo6wv35LWCxhDEy3vFd+/SQPqt/OASSDUVOEGNimtdFuAtoxHBZnbJtVMZSGs1PJBjGrgrxunDqf/oCuutQAVqQIPXRUnhPUKPJIYeCNKGx9rg2WATaSYmMcxplhnkAYSwKLZNQ5hceY6ZxSBIx+3ZEidLNLlRsERbrdIZqSyMVd5G426kcb16cOIG9HCdCFYAB7vSmJMOgSizfuIiAxXrAAc0n/8wBaiak/h0/ZrzdsbnGuEvnMo5t7sppxfbxxx9ytX4ukiRHQD/TMGtCNfdK1nc6TP0paehL6m8TypdVuJWix9ucZatkLmHL/+w/LX74="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
