appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mxTO/V43JgqnJQfNYzSTmJ36ny8SF5gAOr7sr6PmK5EKy/z3wVXYH721tyfOLqxCT8E0m2rmULCkjGFSikrWVwJcDhePaLqlou4sAgAt6a+cVfBdTxZ/NkvlADmrdDIyzdeDJDECHxs+0uDXuAVJ91l+kWXAfoYitoYz9FB4GtZKmbzz5zjoUfkZUp0Bkl03M9xS0qb4c9n8Ud4eWS3vlq8HhPiFY20UCRt5pla+eZ+ijW0x/dqev9xI579ITgoRZJZfa0ODu0Gyh7TnSugBp/qFJ0sJSEBq5kSfc4b4HxTwjArYViwFsq9rrizim3gQDW4O+0ERjguvnrmwCDa3mAJBSGluewj3Fk2mscPzPo6wv35LWCxhDEy3vFd+/SQPqt/OASSDUVOEGNimtdFuAtoxHBZnbJtVMZSGs1PJBjGrgrxunDqf/oCuutQAVqQIPXRUnhPUKPJIYeCNKGx9rg2WATaSYmMcxplhnkAYSwKLZNQ5hceY6ZxSBIx+3ZEidLNLlRsERbrdIZqSyMVd5G426kcb16cOIG9HCdCFYAB7vSmJMOgSizfuIiAxXrAAc0n/8wBaiak/h0/ZrzdsbnGuEvnMo5t7sppxfbxxx9ytX4ukiRHQD/TMGtCNfdK1nc6TP0paehL6m8TypdVuJWix9ucZatkLmHL/+w/LX74=}
conda_forge_output_validation: true
