travis:
  secure:
    BINSTAR_TOKEN: Z185JJOBOTYYVTUK8ZKXSUG99NRaeg5CXCGfYba6rypN5CaQu/yl95oPl2TKlSiY4I7fo7agUx3vXypVuDtZcDRfKvvcne7B9+NAW6AsZi6kQ3NKZ6cBPRzzoYprI7K4fqB+MAviupqEdmip4geoHDiUcQca/ABEs84j9aDmmWxQvVaT9zNqwXaeZXj3JdWstJ5fVV+alqmp+bxIUMXkKY6OKdRptw79VYo6UfYleBvYXL+oUVc6ewLofD4q0FVNsmN0qbIWXFqur7XAWm0AyxXlOVMXka/QRNA310JThBJUWd+8HUXgyZlPJIVDzIufywPCiYFKkFE+pnDpmMAXK5f5F1ZCTYsOwPmNKIYIznWtVsSEc3Z8gvBhX3w9yIxJ7lm9Ak3R6Prb5gpGd7TjLDFsRowqY8+/G1/0vRP/+zJ/nziH0YEoLE4oULroX+CxJ7rZdQcKU+//JZK10T8h2/pQAI931rFJV5FLm2MY42ZVjuP8OpTmn5AgXtmvgpijh7OEXkALJWvDduejrqfbfm6RlhiBtzmvlCT60mKM3YCT137s53jtU3Gck1ogIHCu4AtXBWqTQnleyuUelEeLEJLU/7QDxgPfYZA6uqyTVkxE1G1nNdeAGOaW/kIOPVHo9pMWjXy4uSi7+/mWm8TLOhJo+t1BMdZAlm5KwApmm/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
